// Generated by CoffeeScript 1.6.1
(function() {
  var Auth, PhAuth,
    _this = this,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  if (window.ph.auth) {
    return;
  }

  PhAuth = (function() {

    function PhAuth() {
      var _this = this;
      this._aplCheckCb = function(res) {
        return PhAuth.prototype._aplCheckCb.apply(_this, arguments);
      };
      this._authCheckCb = function(res) {
        return PhAuth.prototype._authCheckCb.apply(_this, arguments);
      };
      this._onMessage = function(ev) {
        return PhAuth.prototype._onMessage.apply(_this, arguments);
      };
      this._alwaysAsyncAuth = function(auth) {
        return PhAuth.prototype._alwaysAsyncAuth.apply(_this, arguments);
      };
    }

    PhAuth.prototype._authFrameName = '__phAuthFrame2';

    PhAuth.prototype._authEachFrameName = '__phEachAuthFrame_';

    PhAuth.prototype._checkAplQuery = '?__PH_AUTH__=__CD_CHECK__';

    PhAuth.prototype._checkWsAplQuery = '?__PH_AUTH__=__CD_WS_CHECK__';

    PhAuth.prototype._urlPtn = /^(?:([^:\/]+:))?(?:\/\/([^\/]*))?(.*)/;

    PhAuth.prototype._auths = {};

    PhAuth.prototype._authQueue = [];

    PhAuth.prototype._processAuth = null;

    PhAuth.prototype._reqUrl = null;

    PhAuth.prototype._reqCb = null;

    PhAuth.prototype._finAuth = function(res) {
      var auth;
      auth = this._processAuth;
      auth.result = res.result;
      if (res.result) {
        auth._setup(res);
      } else {
        auth._deferred.reject(auth);
      }
    };

    PhAuth.prototype._alwaysAsyncAuth = function(auth) {
      if (auth._authCb) {
        auth._authCb(auth);
      }
      this._processAuth = null;
      this._call();
    };

    PhAuth.prototype._callAsyncAuth = function(auth) {
      this._authQueue.push(auth);
      this._call();
    };

    PhAuth.prototype._call = function() {
      var auth;
      if (this._processAuth !== null || this._authQueue.length === 0) {
        return;
      }
      auth = this._authQueue.pop();
      this._processAuth = auth;
      return this._reqestUrl(auth._checkAplUrl, this._aplCheckCb);
    };

    PhAuth.prototype._reqestUrl = function(url, cb) {
      this._reqUrl = url;
      this._reqCb = cb;
      this._frame[0].src = url;
    };

    PhAuth.prototype._reqestCallback = function(res) {
      var reqestCb;
      reqestCb = this._reqCb;
      this._reqUrl = null;
      this._reqCb = null;
      reqestCb(res);
    };

    PhAuth.prototype._init = function() {
      this._frame = ph.jQuery('<iframe width="0" height="0" frameborder="no" name="' + this._authFrameName + '" ></iframe>');
      ph.jQuery("body").append(this._frame);
    };

    PhAuth.prototype._onMessage = function(ev) {
      var res, url;
      if (!this._frame || ev.source !== this._frame[0].contentWindow) {
        return;
      }
      url = this._reqUrl;
      if (!url) {
        return;
      }
      if (url.lastIndexOf(ev.origin, 0) !== 0) {
        return;
      }
      res = ph.JSON.parse(ev.data);
      this._reqestCallback(res);
    };

    PhAuth.prototype._authCheckCb = function(res) {
      if (res.result === 'redirect') {
        this._reqestUrl(res.location, this._authCheckCb);
      } else if (res.result === 'redirectForAuthorizer') {
        window.location.href = res.location;
      } else {
        this._finAuth(res);
      }
    };

    PhAuth.prototype._aplCheckCb = function(res) {
      var redirectUrl;
      if (res.result === 'redirect') {
        redirectUrl = res.location + '&originUrl=' + encodeURIComponent(window.location.href);
        this._reqestUrl(redirectUrl, this._authCheckCb);
      } else {
        this._finAuth(res);
      }
    };

    PhAuth.prototype.auth = function(aplUrl, cb) {
      var auth, authDomain, authObj, authPath, checkAplUrl, dfd, protocol;
      aplUrl.match(this._urlPtn);
      protocol = RegExp.$1;
      authDomain = RegExp.$2;
      authPath = RegExp.$3;
      checkAplUrl = null;
      if (protocol === 'ws:') {
        checkAplUrl = 'http://' + authDomain + authPath + this._checkWsAplQuery;
      } else if (protocol === 'wss:') {
        checkAplUrl = 'https://' + authDomain + authPath + this._checkWsAplQuery;
      } else if (protocol === null || protocol === '') {
        checkAplUrl = window.location.protocol + '//' + window.location.host + authPath + this._checkWsAplQuery;
      } else {
        checkAplUrl = aplUrl + this._checkAplQuery;
      }
      authObj = this._auths[checkAplUrl];
      if (authObj) {
        return authObj.promise;
      }
      dfd = ph.jQuery.Deferred();
      auth = dfd.promise(new Auth(checkAplUrl, dfd));
      auth._checkAplUrl = checkAplUrl;
      auth._authCb = cb;
      auth.always(this._alwaysAsyncAuth);
      this._auths[checkAplUrl] = {
        deferred: dfd,
        promise: auth
      };
      this._callAsyncAuth(auth);
      return auth;
    };

    return PhAuth;

  })();

  window.ph.auth = new PhAuth();

  ph.jQuery(function() {
    ph.auth._init();
    return ph.event.on('message', ph.auth._onMessage);
  });

  Auth = (function(_super) {

    __extends(Auth, _super);

    function Auth(_checkAplUrl, _deferred) {
      var _this = this;
      this._checkAplUrl = _checkAplUrl;
      this._deferred = _deferred;
      this._frameLoad = function() {
        return Auth.prototype._frameLoad.apply(_this, arguments);
      };
      Auth.__super__.constructor.apply(this, arguments);
    }

    Auth.prototype._setup = function(res) {
      this.loginId = res.loginId;
      this.authUrl = res.authUrl;
      this.appSid = res.appSid;
      this.token = res.token;
      this._frame = ph.jQuery('<iframe width="0" height="0" frameborder="no" name="' + ph.auth._authEachFrameName + this._checkAplUrl + '" ></iframe>');
      this._frame.load(this._frameLoad);
      return ph.jQuery("body").append(this._frame);
    };

    Auth.prototype._frameLoad = function() {
      return this._deferred.resolve(this);
    };

    Auth.prototype._onMessage = function() {};

    Auth.prototype.info = function(cb) {};

    Auth.prototype.encrypt = function(loginid, plainText, cb) {};

    Auth.prototype.decrypt = function(loginid, encryptText, cb) {};

    return Auth;

  })(ph.EventModule);

}).call(this);
